logging:
    level:
        org.springframework.web: INFO
        pe.edu.unp: INFO
    file: /log/ruletaservices.log

spring:
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQL9Dialect
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                show-sql: true
                temp.use_jdbc_metadata_defaults: false
    datasource:
        url: jdbc:postgresql://127.0.0.1:5432/ruletaservice
        username: postgres
        password: 123456